### ISSUE TITLE
ProtocolizeItemStackConverter

### ISSUE THREAD

**Issue by Eptiiix** [Simplix-Softworks/Cirrus#1]
Line: 60
Error: cannot get new data of modern material

1.13+ does not have data.getData(); remove or use alternatives like createBlockData() or check for Server ProtocolVersion

**Comment by lackoSK** [comment]
Leonhard... _typing_

**Comment by JavaFactoryDev** [comment]
Hi,
Cirrus is currently in early development. We already solved this in devbuilds:)

Regards,
- Leonhard

**Comment by kangarko** [comment]
@JavaFactoryDev please remove ladislav@mineacademy.org from the email subscriber's list
