### ISSUE TITLE
Clicking any item inside gui with off-hand causes duplication!

### ISSUE THREAD

**Issue by HW2955** [Simplix-Softworks/Cirrus#21]
(Tested with this environment)
Paper-341 (1.18.2)
Java 17.0.3.1
- cirrus-spigot-example-2.0.0
- EssentialxxX-2.19.4
- FAWE-Bukkit-2.3.1
- Skript 2.6.3
- Vault

Actions to replicate:
1. Use the /test command from example usage plugin,
2. Click the 'F' key (switch to off-hand) while cursor is on any item,
2.1. This produces an error ([error.txt](https://github.com/Simplix-Softworks/Cirrus/files/9556090/error.txt))
3. Close the menu,
4. (Note: while player is in survival mode, this only produces a ghost item, though creative mode creates it.)
    Open your inventory (probably works with opening other inventories aswell)
5. Get duplicated item in your off-hand slot.

Hopefully someone smart enough finds a good fix for this, I've fixed this bug in my framework by adding NBT tag to all gui-items and removing them wherever player causes InventoryClickEvent, though i don't find it really optimal solution.

I really love this framework and would love to see it being expanded upon, and documentation being published.

**Comment by KotlinFactory** [comment]
Hi, this Cirrus version is very outdated. Please use 2.1.0+
