### ISSUE TITLE
item disappears when bottomContainer is built

### ISSUE THREAD

**Issue by Eptiiix** [Simplix-Softworks/Cirrus#4]
Hello,

everytime when a player opens a cirrus menu e.g on SkyBlock they loose their items in PlayerInventory from slot 18 to 35.
After researching the problem a few days i found out when i remove 
buildContainer(view.getBottomInventory(), menu.bottomContainer(), true);
in SpigotMenuBuilder.class that there is no problem.

How to reproduce the bug?
Fill your PlayerInventory with items from slot 9 to 35 and open an Cirrus Menu.
You will see that items from slot 18 to 35 will disappear.

**Comment by KotlinFactory** [comment]
Hey Eptiiix,

this should be resolved now. 

Regards,
Leonhard
