### ISSUE TITLE
Method not found: setTag

### ISSUE THREAD

**Issue by Eptiiix** [Simplix-Softworks/Cirrus#9]
java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.setTag(net.minecraft.nbt.NBTTagCompound) - ProtocolizeItemStackConverter.java:109
 
             Method setTag = itemStackNMSClass.getMethod("setTag", nbtTagCompoundClass);

Tested with Paper - 1.18.1 - Reobf
Branch: restructure

**Comment by KotlinFactory** [comment]
Thanks, this was just resolved!
